//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 06:25:41 PM CEST 
//


package ch.so.geo.schema.agi.cadastre._0_9.extract;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BuildingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BuildingType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Egid" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="planned" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="undergroundStructure" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Area" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="AreaShare" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="BuildingEntry" type="{http://geo.so.ch/schema/AGI/Cadastre/0.9/Extract}BuildingEntryType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BuildingType", propOrder = {
    "egid",
    "planned",
    "undergroundStructure",
    "area",
    "areaShare",
    "buildingEntries"
})
public class BuildingType {

    @XmlElement(name = "Egid")
    protected Integer egid;
    protected boolean planned;
    protected boolean undergroundStructure;
    @XmlElement(name = "Area")
    protected Double area;
    @XmlElement(name = "AreaShare")
    protected Double areaShare;
    @XmlElement(name = "BuildingEntry")
    protected List<BuildingEntryType> buildingEntries;

    /**
     * Gets the value of the egid property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEgid() {
        return egid;
    }

    /**
     * Sets the value of the egid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEgid(Integer value) {
        this.egid = value;
    }

    /**
     * Gets the value of the planned property.
     * 
     */
    public boolean isPlanned() {
        return planned;
    }

    /**
     * Sets the value of the planned property.
     * 
     */
    public void setPlanned(boolean value) {
        this.planned = value;
    }

    /**
     * Gets the value of the undergroundStructure property.
     * 
     */
    public boolean isUndergroundStructure() {
        return undergroundStructure;
    }

    /**
     * Sets the value of the undergroundStructure property.
     * 
     */
    public void setUndergroundStructure(boolean value) {
        this.undergroundStructure = value;
    }

    /**
     * Gets the value of the area property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getArea() {
        return area;
    }

    /**
     * Sets the value of the area property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setArea(Double value) {
        this.area = value;
    }

    /**
     * Gets the value of the areaShare property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAreaShare() {
        return areaShare;
    }

    /**
     * Sets the value of the areaShare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAreaShare(Double value) {
        this.areaShare = value;
    }

    /**
     * Gets the value of the buildingEntries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buildingEntries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBuildingEntries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BuildingEntryType }
     * 
     * 
     */
    public List<BuildingEntryType> getBuildingEntries() {
        if (buildingEntries == null) {
            buildingEntries = new ArrayList<BuildingEntryType>();
        }
        return this.buildingEntries;
    }

}
