//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.03 at 06:25:41 PM CEST 
//


package ch.so.geo.schema.agi.cadastre._0_9.extract;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for Map complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Map"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Image" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/&gt;
 *         &lt;element name="ReferenceWMS" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/&gt;
 *         &lt;element name="LegendAtWeb" type="{http://www.w3.org/2001/XMLSchema}anyURI"/&gt;
 *         &lt;element name="min_NS95" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="max_NS95" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Map", propOrder = {
    "image",
    "referenceWMS",
    "legendAtWeb",
    "minNS95",
    "maxNS95"
})
public class Map {

    @XmlElement(name = "Image")
    protected byte[] image;
    @XmlElement(name = "ReferenceWMS")
    @XmlSchemaType(name = "anyURI")
    protected String referenceWMS;
    @XmlElement(name = "LegendAtWeb", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String legendAtWeb;
    @XmlElement(name = "min_NS95", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String minNS95;
    @XmlElement(name = "max_NS95", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String maxNS95;

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setImage(byte[] value) {
        this.image = value;
    }

    /**
     * Gets the value of the referenceWMS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceWMS() {
        return referenceWMS;
    }

    /**
     * Sets the value of the referenceWMS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceWMS(String value) {
        this.referenceWMS = value;
    }

    /**
     * Gets the value of the legendAtWeb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLegendAtWeb() {
        return legendAtWeb;
    }

    /**
     * Sets the value of the legendAtWeb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLegendAtWeb(String value) {
        this.legendAtWeb = value;
    }

    /**
     * Gets the value of the minNS95 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinNS95() {
        return minNS95;
    }

    /**
     * Sets the value of the minNS95 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinNS95(String value) {
        this.minNS95 = value;
    }

    /**
     * Gets the value of the maxNS95 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxNS95() {
        return maxNS95;
    }

    /**
     * Sets the value of the maxNS95 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxNS95(String value) {
        this.maxNS95 = value;
    }

}
