//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConversionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConversionType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractGeneralConversionType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}method"/>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}parameterValue" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConversionType", propOrder = {
    "method",
    "parameterValue"
})
public class ConversionTypeType
    extends AbstractGeneralConversionTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "method", namespace = "http://www.opengis.net/gml/3.2", type = Method.class)
    protected JAXBElement<OperationMethodPropertyTypeType> method;
    @XmlElementRef(name = "parameterValue", namespace = "http://www.opengis.net/gml/3.2", type = ParameterValue.class, required = false)
    protected List<JAXBElement<AbstractGeneralParameterValuePropertyTypeType>> parameterValue;

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link UsesMethod }
     *     {@link Method }
     *     
     */
    public JAXBElement<OperationMethodPropertyTypeType> getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesMethod }
     *     {@link Method }
     *     
     */
    public void setMethod(JAXBElement<OperationMethodPropertyTypeType> value) {
        this.method = value;
    }

    /**
     * Gets the value of the parameterValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IncludesValue }
     * {@link UsesValue }
     * {@link ParameterValue }
     * 
     * 
     */
    public List<JAXBElement<AbstractGeneralParameterValuePropertyTypeType>> getParameterValue() {
        if (parameterValue == null) {
            parameterValue = new ArrayList<JAXBElement<AbstractGeneralParameterValuePropertyTypeType>>();
        }
        return this.parameterValue;
    }

}
