//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CoverageFunctionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoverageFunctionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}MappingRule"/>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}CoverageMappingRule"/>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}GridFunction"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoverageFunctionType", propOrder = {
    "mappingRule",
    "coverageMappingRule",
    "gridFunction"
})
public class CoverageFunctionTypeType implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "MappingRule", namespace = "http://www.opengis.net/gml/3.2", type = MappingRule.class, required = false)
    protected MappingRule mappingRule;
    @XmlElementRef(name = "CoverageMappingRule", namespace = "http://www.opengis.net/gml/3.2", type = CoverageMappingRule.class, required = false)
    protected CoverageMappingRule coverageMappingRule;
    @XmlElementRef(name = "GridFunction", namespace = "http://www.opengis.net/gml/3.2", type = GridFunction.class, required = false)
    protected GridFunction gridFunction;

    /**
     * Gets the value of the mappingRule property.
     * 
     * @return
     *     possible object is
     *     {@link MappingRule }
     *     
     */
    public MappingRule getMappingRule() {
        return mappingRule;
    }

    /**
     * Sets the value of the mappingRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingRule }
     *     
     */
    public void setMappingRule(MappingRule value) {
        this.mappingRule = value;
    }

    /**
     * Gets the value of the coverageMappingRule property.
     * 
     * @return
     *     possible object is
     *     {@link CoverageMappingRule }
     *     
     */
    public CoverageMappingRule getCoverageMappingRule() {
        return coverageMappingRule;
    }

    /**
     * Sets the value of the coverageMappingRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoverageMappingRule }
     *     
     */
    public void setCoverageMappingRule(CoverageMappingRule value) {
        this.coverageMappingRule = value;
    }

    /**
     * Gets the value of the gridFunction property.
     * 
     * @return
     *     possible object is
     *     {@link GridFunction }
     *     
     */
    public GridFunction getGridFunction() {
        return gridFunction;
    }

    /**
     * Sets the value of the gridFunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link GridFunction }
     *     
     */
    public void setGridFunction(GridFunction value) {
        this.gridFunction = value;
    }

}
