//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CubicSplineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CubicSplineType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractCurveSegmentType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;choice maxOccurs="unbounded" minOccurs="2">
 *             &lt;element ref="{http://www.opengis.net/gml/3.2}pos"/>
 *             &lt;element ref="{http://www.opengis.net/gml/3.2}pointProperty"/>
 *             &lt;element ref="{http://www.opengis.net/gml/3.2}pointRep"/>
 *           &lt;/choice>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}posList"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}coordinates"/>
 *         &lt;/choice>
 *         &lt;element name="vectorAtStart" type="{http://www.opengis.net/gml/3.2}VectorType"/>
 *         &lt;element name="vectorAtEnd" type="{http://www.opengis.net/gml/3.2}VectorType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="interpolation" type="{http://www.opengis.net/gml/3.2}CurveInterpolationType" fixed="cubicSpline" />
 *       &lt;attribute name="degree" type="{http://www.w3.org/2001/XMLSchema}integer" fixed="3" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CubicSplineType", propOrder = {
    "posOrPointPropertyOrPointRep",
    "posList",
    "coordinates",
    "vectorAtStart",
    "vectorAtEnd"
})
public class CubicSplineTypeType
    extends AbstractCurveSegmentTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRefs({
        @XmlElementRef(name = "pos", namespace = "http://www.opengis.net/gml/3.2", type = Pos.class, required = false),
        @XmlElementRef(name = "pointRep", namespace = "http://www.opengis.net/gml/3.2", type = PointRep.class, required = false),
        @XmlElementRef(name = "pointProperty", namespace = "http://www.opengis.net/gml/3.2", type = PointProperty.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> posOrPointPropertyOrPointRep;
    @XmlElementRef(name = "posList", namespace = "http://www.opengis.net/gml/3.2", type = PosList.class, required = false)
    protected PosList posList;
    @XmlElementRef(name = "coordinates", namespace = "http://www.opengis.net/gml/3.2", type = Coordinates.class, required = false)
    protected Coordinates coordinates;
    @XmlElement(required = true)
    protected VectorTypeType vectorAtStart;
    @XmlElement(required = true)
    protected VectorTypeType vectorAtEnd;
    @XmlAttribute(name = "interpolation")
    protected CurveInterpolationTypeType interpolation;
    @XmlAttribute(name = "degree")
    protected BigInteger degree;

    /**
     * Gets the value of the posOrPointPropertyOrPointRep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the posOrPointPropertyOrPointRep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPosOrPointPropertyOrPointRep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Pos }
     * {@link PointRep }
     * {@link PointProperty }
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getPosOrPointPropertyOrPointRep() {
        if (posOrPointPropertyOrPointRep == null) {
            posOrPointPropertyOrPointRep = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.posOrPointPropertyOrPointRep;
    }

    /**
     * Gets the value of the posList property.
     * 
     * @return
     *     possible object is
     *     {@link PosList }
     *     
     */
    public PosList getPosList() {
        return posList;
    }

    /**
     * Sets the value of the posList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PosList }
     *     
     */
    public void setPosList(PosList value) {
        this.posList = value;
    }

    /**
     * Gets the value of the coordinates property.
     * 
     * @return
     *     possible object is
     *     {@link Coordinates }
     *     
     */
    public Coordinates getCoordinates() {
        return coordinates;
    }

    /**
     * Sets the value of the coordinates property.
     * 
     * @param value
     *     allowed object is
     *     {@link Coordinates }
     *     
     */
    public void setCoordinates(Coordinates value) {
        this.coordinates = value;
    }

    /**
     * Gets the value of the vectorAtStart property.
     * 
     * @return
     *     possible object is
     *     {@link VectorTypeType }
     *     
     */
    public VectorTypeType getVectorAtStart() {
        return vectorAtStart;
    }

    /**
     * Sets the value of the vectorAtStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorTypeType }
     *     
     */
    public void setVectorAtStart(VectorTypeType value) {
        this.vectorAtStart = value;
    }

    /**
     * Gets the value of the vectorAtEnd property.
     * 
     * @return
     *     possible object is
     *     {@link VectorTypeType }
     *     
     */
    public VectorTypeType getVectorAtEnd() {
        return vectorAtEnd;
    }

    /**
     * Sets the value of the vectorAtEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorTypeType }
     *     
     */
    public void setVectorAtEnd(VectorTypeType value) {
        this.vectorAtEnd = value;
    }

    /**
     * Gets the value of the interpolation property.
     * 
     * @return
     *     possible object is
     *     {@link CurveInterpolationTypeType }
     *     
     */
    public CurveInterpolationTypeType getInterpolation() {
        if (interpolation == null) {
            return CurveInterpolationTypeType.CUBIC_SPLINE;
        } else {
            return interpolation;
        }
    }

    /**
     * Sets the value of the interpolation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurveInterpolationTypeType }
     *     
     */
    public void setInterpolation(CurveInterpolationTypeType value) {
        this.interpolation = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDegree() {
        if (degree == null) {
            return new BigInteger("3");
        } else {
            return degree;
        }
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDegree(BigInteger value) {
        this.degree = value;
    }

}
