//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Direction vectors are specified by providing components of a vector.
 * 
 * <p>Java class for DirectionVectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectionVectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}vector"/>
 *         &lt;sequence>
 *           &lt;element name="horizontalAngle" type="{http://www.opengis.net/gml/3.2}AngleType"/>
 *           &lt;element name="verticalAngle" type="{http://www.opengis.net/gml/3.2}AngleType"/>
 *         &lt;/sequence>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectionVectorType", propOrder = {
    "vector",
    "horizontalAngle",
    "verticalAngle"
})
public class DirectionVectorTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "vector", namespace = "http://www.opengis.net/gml/3.2", type = Vector.class, required = false)
    protected Vector vector;
    protected AngleTypeType horizontalAngle;
    protected AngleTypeType verticalAngle;

    /**
     * Gets the value of the vector property.
     * 
     * @return
     *     possible object is
     *     {@link Vector }
     *     
     */
    public Vector getVector() {
        return vector;
    }

    /**
     * Sets the value of the vector property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vector }
     *     
     */
    public void setVector(Vector value) {
        this.vector = value;
    }

    /**
     * Gets the value of the horizontalAngle property.
     * 
     * @return
     *     possible object is
     *     {@link AngleTypeType }
     *     
     */
    public AngleTypeType getHorizontalAngle() {
        return horizontalAngle;
    }

    /**
     * Sets the value of the horizontalAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleTypeType }
     *     
     */
    public void setHorizontalAngle(AngleTypeType value) {
        this.horizontalAngle = value;
    }

    /**
     * Gets the value of the verticalAngle property.
     * 
     * @return
     *     possible object is
     *     {@link AngleTypeType }
     *     
     */
    public AngleTypeType getVerticalAngle() {
        return verticalAngle;
    }

    /**
     * Sets the value of the verticalAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link AngleTypeType }
     *     
     */
    public void setVerticalAngle(AngleTypeType value) {
        this.verticalAngle = value;
    }

}
