//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EngineeringCRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EngineeringCRSType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractCRSType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}affineCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}cartesianCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}cylindricalCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}linearCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}polarCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}sphericalCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}userDefinedCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}coordinateSystem"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}engineeringDatum"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EngineeringCRSType", propOrder = {
    "affineCS",
    "cartesianCS",
    "cylindricalCS",
    "linearCS",
    "polarCS",
    "sphericalCS",
    "userDefinedCS",
    "coordinateSystem",
    "engineeringDatum"
})
public class EngineeringCRSTypeType
    extends AbstractCRSTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "affineCS", namespace = "http://www.opengis.net/gml/3.2", type = AffineCS.class, required = false)
    protected JAXBElement<AffineCSPropertyTypeType> affineCS;
    @XmlElementRef(name = "cartesianCS", namespace = "http://www.opengis.net/gml/3.2", type = CartesianCS.class, required = false)
    protected JAXBElement<CartesianCSPropertyTypeType> cartesianCS;
    @XmlElementRef(name = "cylindricalCS", namespace = "http://www.opengis.net/gml/3.2", type = CylindricalCS.class, required = false)
    protected CylindricalCS cylindricalCS;
    @XmlElementRef(name = "linearCS", namespace = "http://www.opengis.net/gml/3.2", type = LinearCS.class, required = false)
    protected LinearCS linearCS;
    @XmlElementRef(name = "polarCS", namespace = "http://www.opengis.net/gml/3.2", type = PolarCS.class, required = false)
    protected PolarCS polarCS;
    @XmlElementRef(name = "sphericalCS", namespace = "http://www.opengis.net/gml/3.2", type = SphericalCS.class, required = false)
    protected JAXBElement<SphericalCSPropertyTypeType> sphericalCS;
    @XmlElementRef(name = "userDefinedCS", namespace = "http://www.opengis.net/gml/3.2", type = UserDefinedCS.class, required = false)
    protected UserDefinedCS userDefinedCS;
    @XmlElementRef(name = "coordinateSystem", namespace = "http://www.opengis.net/gml/3.2", type = CoordinateSystem.class, required = false)
    protected JAXBElement<CoordinateSystemPropertyTypeType> coordinateSystem;
    @XmlElementRef(name = "engineeringDatum", namespace = "http://www.opengis.net/gml/3.2", type = EngineeringDatum.class)
    protected JAXBElement<EngineeringDatumPropertyTypeType> engineeringDatum;

    /**
     * Gets the value of the affineCS property.
     * 
     * @return
     *     possible object is
     *     {@link UsesAffineCS }
     *     {@link AffineCS }
     *     
     */
    public JAXBElement<AffineCSPropertyTypeType> getAffineCS() {
        return affineCS;
    }

    /**
     * Sets the value of the affineCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesAffineCS }
     *     {@link AffineCS }
     *     
     */
    public void setAffineCS(JAXBElement<AffineCSPropertyTypeType> value) {
        this.affineCS = value;
    }

    /**
     * Gets the value of the cartesianCS property.
     * 
     * @return
     *     possible object is
     *     {@link UsesCartesianCS }
     *     {@link CartesianCS }
     *     
     */
    public JAXBElement<CartesianCSPropertyTypeType> getCartesianCS() {
        return cartesianCS;
    }

    /**
     * Sets the value of the cartesianCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesCartesianCS }
     *     {@link CartesianCS }
     *     
     */
    public void setCartesianCS(JAXBElement<CartesianCSPropertyTypeType> value) {
        this.cartesianCS = value;
    }

    /**
     * Gets the value of the cylindricalCS property.
     * 
     * @return
     *     possible object is
     *     {@link CylindricalCS }
     *     
     */
    public CylindricalCS getCylindricalCS() {
        return cylindricalCS;
    }

    /**
     * Sets the value of the cylindricalCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link CylindricalCS }
     *     
     */
    public void setCylindricalCS(CylindricalCS value) {
        this.cylindricalCS = value;
    }

    /**
     * Gets the value of the linearCS property.
     * 
     * @return
     *     possible object is
     *     {@link LinearCS }
     *     
     */
    public LinearCS getLinearCS() {
        return linearCS;
    }

    /**
     * Sets the value of the linearCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link LinearCS }
     *     
     */
    public void setLinearCS(LinearCS value) {
        this.linearCS = value;
    }

    /**
     * Gets the value of the polarCS property.
     * 
     * @return
     *     possible object is
     *     {@link PolarCS }
     *     
     */
    public PolarCS getPolarCS() {
        return polarCS;
    }

    /**
     * Sets the value of the polarCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link PolarCS }
     *     
     */
    public void setPolarCS(PolarCS value) {
        this.polarCS = value;
    }

    /**
     * Gets the value of the sphericalCS property.
     * 
     * @return
     *     possible object is
     *     {@link SphericalCS }
     *     {@link UsesSphericalCS }
     *     
     */
    public JAXBElement<SphericalCSPropertyTypeType> getSphericalCS() {
        return sphericalCS;
    }

    /**
     * Sets the value of the sphericalCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link SphericalCS }
     *     {@link UsesSphericalCS }
     *     
     */
    public void setSphericalCS(JAXBElement<SphericalCSPropertyTypeType> value) {
        this.sphericalCS = value;
    }

    /**
     * Gets the value of the userDefinedCS property.
     * 
     * @return
     *     possible object is
     *     {@link UserDefinedCS }
     *     
     */
    public UserDefinedCS getUserDefinedCS() {
        return userDefinedCS;
    }

    /**
     * Sets the value of the userDefinedCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserDefinedCS }
     *     
     */
    public void setUserDefinedCS(UserDefinedCS value) {
        this.userDefinedCS = value;
    }

    /**
     * Gets the value of the coordinateSystem property.
     * 
     * @return
     *     possible object is
     *     {@link UsesCS }
     *     {@link CoordinateSystem }
     *     
     */
    public JAXBElement<CoordinateSystemPropertyTypeType> getCoordinateSystem() {
        return coordinateSystem;
    }

    /**
     * Sets the value of the coordinateSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesCS }
     *     {@link CoordinateSystem }
     *     
     */
    public void setCoordinateSystem(JAXBElement<CoordinateSystemPropertyTypeType> value) {
        this.coordinateSystem = value;
    }

    /**
     * Gets the value of the engineeringDatum property.
     * 
     * @return
     *     possible object is
     *     {@link UsesEngineeringDatum }
     *     {@link EngineeringDatum }
     *     
     */
    public JAXBElement<EngineeringDatumPropertyTypeType> getEngineeringDatum() {
        return engineeringDatum;
    }

    /**
     * Sets the value of the engineeringDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesEngineeringDatum }
     *     {@link EngineeringDatum }
     *     
     */
    public void setEngineeringDatum(JAXBElement<EngineeringDatumPropertyTypeType> value) {
        this.engineeringDatum = value;
    }

}
