//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeocentricCRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeocentricCRSType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractCRSType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}usesCartesianCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}usesSphericalCS"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}usesGeodeticDatum"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeocentricCRSType", propOrder = {
    "usesCartesianCS",
    "usesSphericalCS",
    "usesGeodeticDatum"
})
public class GeocentricCRSTypeType
    extends AbstractCRSTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "usesCartesianCS", namespace = "http://www.opengis.net/gml/3.2", type = UsesCartesianCS.class, required = false)
    protected UsesCartesianCS usesCartesianCS;
    @XmlElementRef(name = "usesSphericalCS", namespace = "http://www.opengis.net/gml/3.2", type = UsesSphericalCS.class, required = false)
    protected UsesSphericalCS usesSphericalCS;
    @XmlElementRef(name = "usesGeodeticDatum", namespace = "http://www.opengis.net/gml/3.2", type = UsesGeodeticDatum.class)
    protected UsesGeodeticDatum usesGeodeticDatum;

    /**
     * Gets the value of the usesCartesianCS property.
     * 
     * @return
     *     possible object is
     *     {@link UsesCartesianCS }
     *     
     */
    public UsesCartesianCS getUsesCartesianCS() {
        return usesCartesianCS;
    }

    /**
     * Sets the value of the usesCartesianCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesCartesianCS }
     *     
     */
    public void setUsesCartesianCS(UsesCartesianCS value) {
        this.usesCartesianCS = value;
    }

    /**
     * Gets the value of the usesSphericalCS property.
     * 
     * @return
     *     possible object is
     *     {@link UsesSphericalCS }
     *     
     */
    public UsesSphericalCS getUsesSphericalCS() {
        return usesSphericalCS;
    }

    /**
     * Sets the value of the usesSphericalCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesSphericalCS }
     *     
     */
    public void setUsesSphericalCS(UsesSphericalCS value) {
        this.usesSphericalCS = value;
    }

    /**
     * Gets the value of the usesGeodeticDatum property.
     * 
     * @return
     *     possible object is
     *     {@link UsesGeodeticDatum }
     *     
     */
    public UsesGeodeticDatum getUsesGeodeticDatum() {
        return usesGeodeticDatum;
    }

    /**
     * Sets the value of the usesGeodeticDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesGeodeticDatum }
     *     
     */
    public void setUsesGeodeticDatum(UsesGeodeticDatum value) {
        this.usesGeodeticDatum = value;
    }

}
