//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * gml:GeodeticCRS is a coordinate reference system based on a geodetic datum.
 * 
 * <p>Java class for GeodeticCRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeodeticCRSType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractCRSType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}ellipsoidalCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}cartesianCS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}sphericalCS"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}geodeticDatum"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeodeticCRSType", propOrder = {
    "ellipsoidalCS",
    "cartesianCS",
    "sphericalCS",
    "geodeticDatum"
})
public class GeodeticCRSTypeType
    extends AbstractCRSTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "ellipsoidalCS", namespace = "http://www.opengis.net/gml/3.2", type = EllipsoidalCS.class, required = false)
    protected JAXBElement<EllipsoidalCSPropertyTypeType> ellipsoidalCS;
    @XmlElementRef(name = "cartesianCS", namespace = "http://www.opengis.net/gml/3.2", type = CartesianCS.class, required = false)
    protected JAXBElement<CartesianCSPropertyTypeType> cartesianCS;
    @XmlElementRef(name = "sphericalCS", namespace = "http://www.opengis.net/gml/3.2", type = SphericalCS.class, required = false)
    protected JAXBElement<SphericalCSPropertyTypeType> sphericalCS;
    @XmlElementRef(name = "geodeticDatum", namespace = "http://www.opengis.net/gml/3.2", type = GeodeticDatum.class)
    protected JAXBElement<GeodeticDatumPropertyTypeType> geodeticDatum;

    /**
     * Gets the value of the ellipsoidalCS property.
     * 
     * @return
     *     possible object is
     *     {@link UsesEllipsoidalCS }
     *     {@link EllipsoidalCS }
     *     
     */
    public JAXBElement<EllipsoidalCSPropertyTypeType> getEllipsoidalCS() {
        return ellipsoidalCS;
    }

    /**
     * Sets the value of the ellipsoidalCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesEllipsoidalCS }
     *     {@link EllipsoidalCS }
     *     
     */
    public void setEllipsoidalCS(JAXBElement<EllipsoidalCSPropertyTypeType> value) {
        this.ellipsoidalCS = value;
    }

    /**
     * Gets the value of the cartesianCS property.
     * 
     * @return
     *     possible object is
     *     {@link UsesCartesianCS }
     *     {@link CartesianCS }
     *     
     */
    public JAXBElement<CartesianCSPropertyTypeType> getCartesianCS() {
        return cartesianCS;
    }

    /**
     * Sets the value of the cartesianCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesCartesianCS }
     *     {@link CartesianCS }
     *     
     */
    public void setCartesianCS(JAXBElement<CartesianCSPropertyTypeType> value) {
        this.cartesianCS = value;
    }

    /**
     * Gets the value of the sphericalCS property.
     * 
     * @return
     *     possible object is
     *     {@link SphericalCS }
     *     {@link UsesSphericalCS }
     *     
     */
    public JAXBElement<SphericalCSPropertyTypeType> getSphericalCS() {
        return sphericalCS;
    }

    /**
     * Sets the value of the sphericalCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link SphericalCS }
     *     {@link UsesSphericalCS }
     *     
     */
    public void setSphericalCS(JAXBElement<SphericalCSPropertyTypeType> value) {
        this.sphericalCS = value;
    }

    /**
     * Gets the value of the geodeticDatum property.
     * 
     * @return
     *     possible object is
     *     {@link UsesGeodeticDatum }
     *     {@link GeodeticDatum }
     *     
     */
    public JAXBElement<GeodeticDatumPropertyTypeType> getGeodeticDatum() {
        return geodeticDatum;
    }

    /**
     * Sets the value of the geodeticDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesGeodeticDatum }
     *     {@link GeodeticDatum }
     *     
     */
    public void setGeodeticDatum(JAXBElement<GeodeticDatumPropertyTypeType> value) {
        this.geodeticDatum = value;
    }

}
