//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import ch.ehi.oereb.schemas.xlink._1999.ActuateType;
import ch.ehi.oereb.schemas.xlink._1999.ShowType;
import ch.ehi.oereb.schemas.xlink._1999.TypeType;


/**
 * <p>Java class for LocationPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocationPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}AbstractGeometry"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}LocationKeyWord"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}LocationString"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}Null"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.opengis.net/gml/3.2}AssociationAttributeGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocationPropertyType", propOrder = {
    "abstractGeometry",
    "locationKeyWord",
    "locationString",
    "_null"
})
@XmlSeeAlso({
    PriorityLocationPropertyTypeType.class
})
public class LocationPropertyTypeType implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "AbstractGeometry", namespace = "http://www.opengis.net/gml/3.2", type = AbstractGeometry.class, required = false)
    protected JAXBElement<? extends AbstractGeometryTypeType> abstractGeometry;
    @XmlElementRef(name = "LocationKeyWord", namespace = "http://www.opengis.net/gml/3.2", type = LocationKeyWord.class, required = false)
    protected LocationKeyWord locationKeyWord;
    @XmlElementRef(name = "LocationString", namespace = "http://www.opengis.net/gml/3.2", type = LocationString.class, required = false)
    protected LocationString locationString;
    @XmlElementRef(name = "Null", namespace = "http://www.opengis.net/gml/3.2", type = Null.class, required = false)
    protected List<Null> _null;
    @XmlAttribute(name = "nilReason")
    protected List<String> nilReason;
    @XmlAttribute(name = "remoteSchema", namespace = "http://www.opengis.net/gml/3.2")
    @XmlSchemaType(name = "anyURI")
    protected String remoteSchema;
    @XmlAttribute(name = "type", namespace = "http://www.w3.org/1999/xlink")
    protected TypeType type;
    @XmlAttribute(name = "href", namespace = "http://www.w3.org/1999/xlink")
    protected String href;
    @XmlAttribute(name = "role", namespace = "http://www.w3.org/1999/xlink")
    protected String role;
    @XmlAttribute(name = "arcrole", namespace = "http://www.w3.org/1999/xlink")
    protected String arcrole;
    @XmlAttribute(name = "title", namespace = "http://www.w3.org/1999/xlink")
    protected String title;
    @XmlAttribute(name = "show", namespace = "http://www.w3.org/1999/xlink")
    protected ShowType show;
    @XmlAttribute(name = "actuate", namespace = "http://www.w3.org/1999/xlink")
    protected ActuateType actuate;

    /**
     * Gets the value of the abstractGeometry property.
     * 
     * @return
     *     possible object is
     *     {@link RectifiedGrid }
     *     {@link MultiSurface }
     *     {@link CompositeSolid }
     *     {@link TriangulatedSurface }
     *     {@link LineString }
     *     {@link LinearRing }
     *     {@link AbstractSolid }
     *     {@link AbstractRing }
     *     {@link MultiGeometry }
     *     {@link OrientableCurve }
     *     {@link GeometricComplex }
     *     {@link CompositeSurface }
     *     {@link AbstractGeometricPrimitive }
     *     {@link AbstractGeometricAggregate }
     *     {@link AbstractSurface }
     *     {@link MultiPoint }
     *     {@link Curve }
     *     {@link Shell }
     *     {@link AbstractImplicitGeometry }
     *     {@link MultiCurve }
     *     {@link AbstractGeometry }
     *     {@link Surface }
     *     {@link Point }
     *     {@link AbstractCurve }
     *     {@link Ring }
     *     {@link Solid }
     *     {@link CompositeCurve }
     *     {@link Tin }
     *     {@link Polygon }
     *     {@link MultiSolid }
     *     {@link OrientableSurface }
     *     {@link Grid }
     *     {@link PolyhedralSurface }
     *     
     */
    public JAXBElement<? extends AbstractGeometryTypeType> getAbstractGeometry() {
        return abstractGeometry;
    }

    /**
     * Sets the value of the abstractGeometry property.
     * 
     * @param value
     *     allowed object is
     *     {@link RectifiedGrid }
     *     {@link MultiSurface }
     *     {@link CompositeSolid }
     *     {@link TriangulatedSurface }
     *     {@link LineString }
     *     {@link LinearRing }
     *     {@link AbstractSolid }
     *     {@link AbstractRing }
     *     {@link MultiGeometry }
     *     {@link OrientableCurve }
     *     {@link GeometricComplex }
     *     {@link CompositeSurface }
     *     {@link AbstractGeometricPrimitive }
     *     {@link AbstractGeometricAggregate }
     *     {@link AbstractSurface }
     *     {@link MultiPoint }
     *     {@link Curve }
     *     {@link Shell }
     *     {@link AbstractImplicitGeometry }
     *     {@link MultiCurve }
     *     {@link AbstractGeometry }
     *     {@link Surface }
     *     {@link Point }
     *     {@link AbstractCurve }
     *     {@link Ring }
     *     {@link Solid }
     *     {@link CompositeCurve }
     *     {@link Tin }
     *     {@link Polygon }
     *     {@link MultiSolid }
     *     {@link OrientableSurface }
     *     {@link Grid }
     *     {@link PolyhedralSurface }
     *     
     */
    public void setAbstractGeometry(JAXBElement<? extends AbstractGeometryTypeType> value) {
        this.abstractGeometry = value;
    }

    /**
     * Gets the value of the locationKeyWord property.
     * 
     * @return
     *     possible object is
     *     {@link LocationKeyWord }
     *     
     */
    public LocationKeyWord getLocationKeyWord() {
        return locationKeyWord;
    }

    /**
     * Sets the value of the locationKeyWord property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationKeyWord }
     *     
     */
    public void setLocationKeyWord(LocationKeyWord value) {
        this.locationKeyWord = value;
    }

    /**
     * Gets the value of the locationString property.
     * 
     * @return
     *     possible object is
     *     {@link LocationString }
     *     
     */
    public LocationString getLocationString() {
        return locationString;
    }

    /**
     * Sets the value of the locationString property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationString }
     *     
     */
    public void setLocationString(LocationString value) {
        this.locationString = value;
    }

    /**
     * Gets the value of the null property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the null property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNull().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Null }
     * 
     * 
     */
    public List<Null> getNull() {
        if (_null == null) {
            _null = new ArrayList<Null>();
        }
        return this._null;
    }

    /**
     * Gets the value of the nilReason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nilReason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNilReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getNilReason() {
        if (nilReason == null) {
            nilReason = new ArrayList<String>();
        }
        return this.nilReason;
    }

    /**
     * Gets the value of the remoteSchema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemoteSchema() {
        return remoteSchema;
    }

    /**
     * Sets the value of the remoteSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemoteSchema(String value) {
        this.remoteSchema = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TypeType }
     *     
     */
    public TypeType getType() {
        if (type == null) {
            return TypeType.SIMPLE;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeType }
     *     
     */
    public void setType(TypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRole(String value) {
        this.role = value;
    }

    /**
     * Gets the value of the arcrole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArcrole() {
        return arcrole;
    }

    /**
     * Sets the value of the arcrole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArcrole(String value) {
        this.arcrole = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the show property.
     * 
     * @return
     *     possible object is
     *     {@link ShowType }
     *     
     */
    public ShowType getShow() {
        return show;
    }

    /**
     * Sets the value of the show property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShowType }
     *     
     */
    public void setShow(ShowType value) {
        this.show = value;
    }

    /**
     * Gets the value of the actuate property.
     * 
     * @return
     *     possible object is
     *     {@link ActuateType }
     *     
     */
    public ActuateType getActuate() {
        return actuate;
    }

    /**
     * Sets the value of the actuate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActuateType }
     *     
     */
    public void setActuate(ActuateType value) {
        this.actuate = value;
    }

}
