//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MovingObjectStatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MovingObjectStatusType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractTimeSliceType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="position" type="{http://www.opengis.net/gml/3.2}GeometryPropertyType"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}pos"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}locationName"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}locationReference"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}location"/>
 *         &lt;/choice>
 *         &lt;element name="speed" type="{http://www.opengis.net/gml/3.2}MeasureType" minOccurs="0"/>
 *         &lt;element name="bearing" type="{http://www.opengis.net/gml/3.2}DirectionPropertyType" minOccurs="0"/>
 *         &lt;element name="acceleration" type="{http://www.opengis.net/gml/3.2}MeasureType" minOccurs="0"/>
 *         &lt;element name="elevation" type="{http://www.opengis.net/gml/3.2}MeasureType" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}status" minOccurs="0"/>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}statusReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MovingObjectStatusType", propOrder = {
    "position",
    "pos",
    "locationName",
    "locationReference",
    "location",
    "speed",
    "bearing",
    "acceleration",
    "elevation",
    "status",
    "statusReference"
})
public class MovingObjectStatusTypeType
    extends AbstractTimeSliceTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected GeometryPropertyTypeType position;
    @XmlElementRef(name = "pos", namespace = "http://www.opengis.net/gml/3.2", type = Pos.class, required = false)
    protected Pos pos;
    @XmlElementRef(name = "locationName", namespace = "http://www.opengis.net/gml/3.2", type = LocationName.class, required = false)
    protected LocationName locationName;
    @XmlElementRef(name = "locationReference", namespace = "http://www.opengis.net/gml/3.2", type = LocationReference.class, required = false)
    protected LocationReference locationReference;
    @XmlElementRef(name = "location", namespace = "http://www.opengis.net/gml/3.2", type = Location.class, required = false)
    protected JAXBElement<? extends LocationPropertyTypeType> location;
    protected MeasureTypeType speed;
    protected DirectionPropertyTypeType bearing;
    protected MeasureTypeType acceleration;
    protected MeasureTypeType elevation;
    @XmlElementRef(name = "status", namespace = "http://www.opengis.net/gml/3.2", type = Status.class, required = false)
    protected Status status;
    @XmlElementRef(name = "statusReference", namespace = "http://www.opengis.net/gml/3.2", type = StatusReference.class, required = false)
    protected StatusReference statusReference;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link GeometryPropertyTypeType }
     *     
     */
    public GeometryPropertyTypeType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometryPropertyTypeType }
     *     
     */
    public void setPosition(GeometryPropertyTypeType value) {
        this.position = value;
    }

    /**
     * Gets the value of the pos property.
     * 
     * @return
     *     possible object is
     *     {@link Pos }
     *     
     */
    public Pos getPos() {
        return pos;
    }

    /**
     * Sets the value of the pos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pos }
     *     
     */
    public void setPos(Pos value) {
        this.pos = value;
    }

    /**
     * Gets the value of the locationName property.
     * 
     * @return
     *     possible object is
     *     {@link LocationName }
     *     
     */
    public LocationName getLocationName() {
        return locationName;
    }

    /**
     * Sets the value of the locationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationName }
     *     
     */
    public void setLocationName(LocationName value) {
        this.locationName = value;
    }

    /**
     * Gets the value of the locationReference property.
     * 
     * @return
     *     possible object is
     *     {@link LocationReference }
     *     
     */
    public LocationReference getLocationReference() {
        return locationReference;
    }

    /**
     * Sets the value of the locationReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationReference }
     *     
     */
    public void setLocationReference(LocationReference value) {
        this.locationReference = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     {@link PriorityLocation }
     *     
     */
    public JAXBElement<? extends LocationPropertyTypeType> getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     {@link PriorityLocation }
     *     
     */
    public void setLocation(JAXBElement<? extends LocationPropertyTypeType> value) {
        this.location = value;
    }

    /**
     * Gets the value of the speed property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureTypeType }
     *     
     */
    public MeasureTypeType getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the speed property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureTypeType }
     *     
     */
    public void setSpeed(MeasureTypeType value) {
        this.speed = value;
    }

    /**
     * Gets the value of the bearing property.
     * 
     * @return
     *     possible object is
     *     {@link DirectionPropertyTypeType }
     *     
     */
    public DirectionPropertyTypeType getBearing() {
        return bearing;
    }

    /**
     * Sets the value of the bearing property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectionPropertyTypeType }
     *     
     */
    public void setBearing(DirectionPropertyTypeType value) {
        this.bearing = value;
    }

    /**
     * Gets the value of the acceleration property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureTypeType }
     *     
     */
    public MeasureTypeType getAcceleration() {
        return acceleration;
    }

    /**
     * Sets the value of the acceleration property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureTypeType }
     *     
     */
    public void setAcceleration(MeasureTypeType value) {
        this.acceleration = value;
    }

    /**
     * Gets the value of the elevation property.
     * 
     * @return
     *     possible object is
     *     {@link MeasureTypeType }
     *     
     */
    public MeasureTypeType getElevation() {
        return elevation;
    }

    /**
     * Sets the value of the elevation property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasureTypeType }
     *     
     */
    public void setElevation(MeasureTypeType value) {
        this.elevation = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusReference property.
     * 
     * @return
     *     possible object is
     *     {@link StatusReference }
     *     
     */
    public StatusReference getStatusReference() {
        return statusReference;
    }

    /**
     * Sets the value of the statusReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusReference }
     *     
     */
    public void setStatusReference(StatusReference value) {
        this.statusReference = value;
    }

}
