//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OffsetCurveType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OffsetCurveType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractCurveSegmentType">
 *       &lt;sequence>
 *         &lt;element name="offsetBase" type="{http://www.opengis.net/gml/3.2}CurvePropertyType"/>
 *         &lt;element name="distance" type="{http://www.opengis.net/gml/3.2}LengthType"/>
 *         &lt;element name="refDirection" type="{http://www.opengis.net/gml/3.2}VectorType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OffsetCurveType", propOrder = {
    "offsetBase",
    "distance",
    "refDirection"
})
public class OffsetCurveTypeType
    extends AbstractCurveSegmentTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected CurvePropertyTypeType offsetBase;
    @XmlElement(required = true)
    protected LengthTypeType distance;
    protected VectorTypeType refDirection;

    /**
     * Gets the value of the offsetBase property.
     * 
     * @return
     *     possible object is
     *     {@link CurvePropertyTypeType }
     *     
     */
    public CurvePropertyTypeType getOffsetBase() {
        return offsetBase;
    }

    /**
     * Sets the value of the offsetBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurvePropertyTypeType }
     *     
     */
    public void setOffsetBase(CurvePropertyTypeType value) {
        this.offsetBase = value;
    }

    /**
     * Gets the value of the distance property.
     * 
     * @return
     *     possible object is
     *     {@link LengthTypeType }
     *     
     */
    public LengthTypeType getDistance() {
        return distance;
    }

    /**
     * Sets the value of the distance property.
     * 
     * @param value
     *     allowed object is
     *     {@link LengthTypeType }
     *     
     */
    public void setDistance(LengthTypeType value) {
        this.distance = value;
    }

    /**
     * Gets the value of the refDirection property.
     * 
     * @return
     *     possible object is
     *     {@link VectorTypeType }
     *     
     */
    public VectorTypeType getRefDirection() {
        return refDirection;
    }

    /**
     * Sets the value of the refDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link VectorTypeType }
     *     
     */
    public void setRefDirection(VectorTypeType value) {
        this.refDirection = value;
    }

}
