//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParameterValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterValueType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractGeneralParameterValueType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}value"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}dmsAngleValue"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}stringValue"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}integerValue"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}booleanValue"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}valueList"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}integerValueList"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}valueFile"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}operationParameter"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterValueType", propOrder = {
    "value",
    "dmsAngleValue",
    "stringValue",
    "integerValue",
    "booleanValue",
    "valueList",
    "integerValueList",
    "valueFile",
    "operationParameter"
})
public class ParameterValueTypeType
    extends AbstractGeneralParameterValueTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "value", namespace = "http://www.opengis.net/gml/3.2", type = Value.class, required = false)
    protected Value value;
    @XmlElementRef(name = "dmsAngleValue", namespace = "http://www.opengis.net/gml/3.2", type = DmsAngleValue.class, required = false)
    protected DmsAngleValue dmsAngleValue;
    @XmlElementRef(name = "stringValue", namespace = "http://www.opengis.net/gml/3.2", type = StringValue.class, required = false)
    protected StringValue stringValue;
    @XmlElementRef(name = "integerValue", namespace = "http://www.opengis.net/gml/3.2", type = IntegerValue.class, required = false)
    protected IntegerValue integerValue;
    @XmlElementRef(name = "booleanValue", namespace = "http://www.opengis.net/gml/3.2", type = BooleanValue.class, required = false)
    protected BooleanValue booleanValue;
    @XmlElementRef(name = "valueList", namespace = "http://www.opengis.net/gml/3.2", type = ValueList.class, required = false)
    protected ValueList valueList;
    @XmlElementRef(name = "integerValueList", namespace = "http://www.opengis.net/gml/3.2", type = IntegerValueList.class, required = false)
    protected List<IntegerValueList> integerValueList;
    @XmlElementRef(name = "valueFile", namespace = "http://www.opengis.net/gml/3.2", type = ValueFile.class, required = false)
    protected ValueFile valueFile;
    @XmlElementRef(name = "operationParameter", namespace = "http://www.opengis.net/gml/3.2", type = OperationParameter.class)
    protected JAXBElement<OperationParameterPropertyTypeType> operationParameter;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Value }
     *     
     */
    public Value getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Value }
     *     
     */
    public void setValue(Value value) {
        this.value = value;
    }

    /**
     * Gets the value of the dmsAngleValue property.
     * 
     * @return
     *     possible object is
     *     {@link DmsAngleValue }
     *     
     */
    public DmsAngleValue getDmsAngleValue() {
        return dmsAngleValue;
    }

    /**
     * Sets the value of the dmsAngleValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmsAngleValue }
     *     
     */
    public void setDmsAngleValue(DmsAngleValue value) {
        this.dmsAngleValue = value;
    }

    /**
     * Gets the value of the stringValue property.
     * 
     * @return
     *     possible object is
     *     {@link StringValue }
     *     
     */
    public StringValue getStringValue() {
        return stringValue;
    }

    /**
     * Sets the value of the stringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValue }
     *     
     */
    public void setStringValue(StringValue value) {
        this.stringValue = value;
    }

    /**
     * Gets the value of the integerValue property.
     * 
     * @return
     *     possible object is
     *     {@link IntegerValue }
     *     
     */
    public IntegerValue getIntegerValue() {
        return integerValue;
    }

    /**
     * Sets the value of the integerValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegerValue }
     *     
     */
    public void setIntegerValue(IntegerValue value) {
        this.integerValue = value;
    }

    /**
     * Gets the value of the booleanValue property.
     * 
     * @return
     *     possible object is
     *     {@link BooleanValue }
     *     
     */
    public BooleanValue getBooleanValue() {
        return booleanValue;
    }

    /**
     * Sets the value of the booleanValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BooleanValue }
     *     
     */
    public void setBooleanValue(BooleanValue value) {
        this.booleanValue = value;
    }

    /**
     * Gets the value of the valueList property.
     * 
     * @return
     *     possible object is
     *     {@link ValueList }
     *     
     */
    public ValueList getValueList() {
        return valueList;
    }

    /**
     * Sets the value of the valueList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueList }
     *     
     */
    public void setValueList(ValueList value) {
        this.valueList = value;
    }

    /**
     * Gets the value of the integerValueList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the integerValueList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntegerValueList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IntegerValueList }
     * 
     * 
     */
    public List<IntegerValueList> getIntegerValueList() {
        if (integerValueList == null) {
            integerValueList = new ArrayList<IntegerValueList>();
        }
        return this.integerValueList;
    }

    /**
     * Gets the value of the valueFile property.
     * 
     * @return
     *     possible object is
     *     {@link ValueFile }
     *     
     */
    public ValueFile getValueFile() {
        return valueFile;
    }

    /**
     * Sets the value of the valueFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueFile }
     *     
     */
    public void setValueFile(ValueFile value) {
        this.valueFile = value;
    }

    /**
     * Gets the value of the operationParameter property.
     * 
     * @return
     *     possible object is
     *     {@link OperationParameter }
     *     {@link ValueOfParameter }
     *     
     */
    public JAXBElement<OperationParameterPropertyTypeType> getOperationParameter() {
        return operationParameter;
    }

    /**
     * Sets the value of the operationParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationParameter }
     *     {@link ValueOfParameter }
     *     
     */
    public void setOperationParameter(JAXBElement<OperationParameterPropertyTypeType> value) {
        this.operationParameter = value;
    }

}
