//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProjectedCRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProjectedCRSType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractGeneralDerivedCRSType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}baseGeodeticCRS"/>
 *           &lt;element ref="{http://www.opengis.net/gml/3.2}baseGeographicCRS"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}cartesianCS"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProjectedCRSType", propOrder = {
    "baseGeodeticCRS",
    "baseGeographicCRS",
    "cartesianCS"
})
public class ProjectedCRSTypeType
    extends AbstractGeneralDerivedCRSTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "baseGeodeticCRS", namespace = "http://www.opengis.net/gml/3.2", type = BaseGeodeticCRS.class, required = false)
    protected BaseGeodeticCRS baseGeodeticCRS;
    @XmlElementRef(name = "baseGeographicCRS", namespace = "http://www.opengis.net/gml/3.2", type = BaseGeographicCRS.class, required = false)
    protected BaseGeographicCRS baseGeographicCRS;
    @XmlElementRef(name = "cartesianCS", namespace = "http://www.opengis.net/gml/3.2", type = CartesianCS.class)
    protected JAXBElement<CartesianCSPropertyTypeType> cartesianCS;

    /**
     * Gets the value of the baseGeodeticCRS property.
     * 
     * @return
     *     possible object is
     *     {@link BaseGeodeticCRS }
     *     
     */
    public BaseGeodeticCRS getBaseGeodeticCRS() {
        return baseGeodeticCRS;
    }

    /**
     * Sets the value of the baseGeodeticCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseGeodeticCRS }
     *     
     */
    public void setBaseGeodeticCRS(BaseGeodeticCRS value) {
        this.baseGeodeticCRS = value;
    }

    /**
     * Gets the value of the baseGeographicCRS property.
     * 
     * @return
     *     possible object is
     *     {@link BaseGeographicCRS }
     *     
     */
    public BaseGeographicCRS getBaseGeographicCRS() {
        return baseGeographicCRS;
    }

    /**
     * Sets the value of the baseGeographicCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaseGeographicCRS }
     *     
     */
    public void setBaseGeographicCRS(BaseGeographicCRS value) {
        this.baseGeographicCRS = value;
    }

    /**
     * Gets the value of the cartesianCS property.
     * 
     * @return
     *     possible object is
     *     {@link UsesCartesianCS }
     *     {@link CartesianCS }
     *     
     */
    public JAXBElement<CartesianCSPropertyTypeType> getCartesianCS() {
        return cartesianCS;
    }

    /**
     * Sets the value of the cartesianCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesCartesianCS }
     *     {@link CartesianCS }
     *     
     */
    public void setCartesianCS(JAXBElement<CartesianCSPropertyTypeType> value) {
        this.cartesianCS = value;
    }

}
