//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.gml._3_2;

import java.io.Serializable;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerticalCRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerticalCRSType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractCRSType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}verticalCS"/>
 *         &lt;element ref="{http://www.opengis.net/gml/3.2}verticalDatum"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerticalCRSType", propOrder = {
    "verticalCS",
    "verticalDatum"
})
public class VerticalCRSTypeType
    extends AbstractCRSTypeType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElementRef(name = "verticalCS", namespace = "http://www.opengis.net/gml/3.2", type = VerticalCS.class)
    protected JAXBElement<VerticalCSPropertyTypeType> verticalCS;
    @XmlElementRef(name = "verticalDatum", namespace = "http://www.opengis.net/gml/3.2", type = VerticalDatum.class)
    protected JAXBElement<VerticalDatumPropertyTypeType> verticalDatum;

    /**
     * Gets the value of the verticalCS property.
     * 
     * @return
     *     possible object is
     *     {@link UsesVerticalCS }
     *     {@link VerticalCS }
     *     
     */
    public JAXBElement<VerticalCSPropertyTypeType> getVerticalCS() {
        return verticalCS;
    }

    /**
     * Sets the value of the verticalCS property.
     * 
     * @param value
     *     allowed object is
     *     {@link UsesVerticalCS }
     *     {@link VerticalCS }
     *     
     */
    public void setVerticalCS(JAXBElement<VerticalCSPropertyTypeType> value) {
        this.verticalCS = value;
    }

    /**
     * Gets the value of the verticalDatum property.
     * 
     * @return
     *     possible object is
     *     {@link VerticalDatum }
     *     {@link UsesVerticalDatum }
     *     
     */
    public JAXBElement<VerticalDatumPropertyTypeType> getVerticalDatum() {
        return verticalDatum;
    }

    /**
     * Sets the value of the verticalDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerticalDatum }
     *     {@link UsesVerticalDatum }
     *     
     */
    public void setVerticalDatum(JAXBElement<VerticalDatumPropertyTypeType> value) {
        this.verticalDatum = value;
    }

}
