//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.oereb._1_0.extractdata;

import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ch.ehi.oereb.schemas.oereb._1_0.extractdata package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ch.ehi.oereb.schemas.oereb._1_0.extractdata
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Extensions }
     * 
     */
    public Extensions createExtensions() {
        return new Extensions();
    }

    /**
     * Create an instance of {@link ExtractType }
     * 
     */
    public ExtractType createExtractType() {
        return new ExtractType();
    }

    /**
     * Create an instance of {@link OfficeType }
     * 
     */
    public OfficeType createOfficeType() {
        return new OfficeType();
    }

    /**
     * Create an instance of {@link LawstatusType }
     * 
     */
    public LawstatusType createLawstatusType() {
        return new LawstatusType();
    }

    /**
     * Create an instance of {@link ArticleType }
     * 
     */
    public ArticleType createArticleType() {
        return new ArticleType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link LocalisedMTextType }
     * 
     */
    public LocalisedMTextType createLocalisedMTextType() {
        return new LocalisedMTextType();
    }

    /**
     * Create an instance of {@link LegendEntryType }
     * 
     */
    public LegendEntryType createLegendEntryType() {
        return new LegendEntryType();
    }

    /**
     * Create an instance of {@link MultilingualTextType }
     * 
     */
    public MultilingualTextType createMultilingualTextType() {
        return new MultilingualTextType();
    }

    /**
     * Create an instance of {@link LocalisedUriType }
     * 
     */
    public LocalisedUriType createLocalisedUriType() {
        return new LocalisedUriType();
    }

    /**
     * Create an instance of {@link DocumentBaseType }
     * 
     */
    public DocumentBaseType createDocumentBaseType() {
        return new DocumentBaseType();
    }

    /**
     * Create an instance of {@link RestrictionOnLandownershipType }
     * 
     */
    public RestrictionOnLandownershipType createRestrictionOnLandownershipType() {
        return new RestrictionOnLandownershipType();
    }

    /**
     * Create an instance of {@link GeometryType }
     * 
     */
    public GeometryType createGeometryType() {
        return new GeometryType();
    }

    /**
     * Create an instance of {@link RealEstateDPRType }
     * 
     */
    public RealEstateDPRType createRealEstateDPRType() {
        return new RealEstateDPRType();
    }

    /**
     * Create an instance of {@link WebReferenceType }
     * 
     */
    public WebReferenceType createWebReferenceType() {
        return new WebReferenceType();
    }

    /**
     * Create an instance of {@link MultilingualUriType }
     * 
     */
    public MultilingualUriType createMultilingualUriType() {
        return new MultilingualUriType();
    }

    /**
     * Create an instance of {@link ExclusionOfLiabilityType }
     * 
     */
    public ExclusionOfLiabilityType createExclusionOfLiabilityType() {
        return new ExclusionOfLiabilityType();
    }

    /**
     * Create an instance of {@link MultilingualMTextType }
     * 
     */
    public MultilingualMTextType createMultilingualMTextType() {
        return new MultilingualMTextType();
    }

    /**
     * Create an instance of {@link GlossaryType }
     * 
     */
    public GlossaryType createGlossaryType() {
        return new GlossaryType();
    }

    /**
     * Create an instance of {@link ThemeType }
     * 
     */
    public ThemeType createThemeType() {
        return new ThemeType();
    }

    /**
     * Create an instance of {@link LocalisedTextType }
     * 
     */
    public LocalisedTextType createLocalisedTextType() {
        return new LocalisedTextType();
    }

    /**
     * Create an instance of {@link MapType }
     * 
     */
    public MapType createMapType() {
        return new MapType();
    }

    /**
     * Create an instance of {@link Extract }}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData", name = "Extract")
    public Extract createExtract(ExtractType value) {
        return new Extract(value);
    }

}
