//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.28 at 05:34:43 PM CEST 
//


package ch.ehi.oereb.schemas.oereb._1_0.extractdata;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import ch.ehi.oereb.schemas.gml._3_2.MultiSurfacePropertyTypeType;


/**
 * <p>Java class for RealEstate_DPR complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RealEstate_DPR">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Number" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IdentDN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EGRID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *               &lt;maxLength value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Type" type="{http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData}RealEstateType"/>
 *         &lt;element name="Canton" type="{http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData}CantonCode"/>
 *         &lt;element name="Municipality">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SubunitOfLandRegister" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FosNr" type="{http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData}MunicipalityCode"/>
 *         &lt;element name="MetadataOfGeographicalBaseData" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="LandRegistryArea" type="{http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData}Area"/>
 *         &lt;element name="Limit" type="{http://www.opengis.net/gml/3.2}MultiSurfacePropertyType" minOccurs="0"/>
 *         &lt;element name="RestrictionOnLandownership" type="{http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData}RestrictionOnLandownership" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PlanForLandRegister" type="{http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData}Map"/>
 *         &lt;element name="PlanForLandRegisterMainPage" type="{http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData}Map"/>
 *         &lt;element name="Reference" type="{http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData}Document" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://schemas.geo.admin.ch/V_D/OeREB/1.0/ExtractData}extensions" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RealEstate_DPR", propOrder = {
    "number",
    "identDN",
    "egrid",
    "type",
    "canton",
    "municipality",
    "subunitOfLandRegister",
    "fosNr",
    "metadataOfGeographicalBaseData",
    "landRegistryArea",
    "limit",
    "restrictionOnLandownership",
    "planForLandRegister",
    "planForLandRegisterMainPage",
    "reference",
    "extensions"
})
public class RealEstateDPRType
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Number")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String number;
    @XmlElement(name = "IdentDN")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String identDN;
    @XmlElement(name = "EGRID")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String egrid;
    @XmlElement(name = "Type", required = true)
    protected RealEstateTypeType type;
    @XmlElement(name = "Canton", required = true)
    protected CantonCodeType canton;
    @XmlElement(name = "Municipality", required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String municipality;
    @XmlElement(name = "SubunitOfLandRegister")
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    protected String subunitOfLandRegister;
    @XmlElement(name = "FosNr")
    protected int fosNr;
    @XmlElement(name = "MetadataOfGeographicalBaseData")
    @XmlSchemaType(name = "anyURI")
    protected String metadataOfGeographicalBaseData;
    @XmlElement(name = "LandRegistryArea")
    protected int landRegistryArea;
    @XmlElement(name = "Limit")
    protected MultiSurfacePropertyTypeType limit;
    @XmlElement(name = "RestrictionOnLandownership")
    protected List<RestrictionOnLandownershipType> restrictionOnLandownership;
    @XmlElement(name = "PlanForLandRegister", required = true)
    protected MapType planForLandRegister;
    @XmlElement(name = "PlanForLandRegisterMainPage", required = true)
    protected MapType planForLandRegisterMainPage;
    @XmlElement(name = "Reference")
    protected List<DocumentType> reference;
    protected Extensions extensions;

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the identDN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentDN() {
        return identDN;
    }

    /**
     * Sets the value of the identDN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentDN(String value) {
        this.identDN = value;
    }

    /**
     * Gets the value of the egrid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEGRID() {
        return egrid;
    }

    /**
     * Sets the value of the egrid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEGRID(String value) {
        this.egrid = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link RealEstateTypeType }
     *     
     */
    public RealEstateTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealEstateTypeType }
     *     
     */
    public void setType(RealEstateTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the canton property.
     * 
     * @return
     *     possible object is
     *     {@link CantonCodeType }
     *     
     */
    public CantonCodeType getCanton() {
        return canton;
    }

    /**
     * Sets the value of the canton property.
     * 
     * @param value
     *     allowed object is
     *     {@link CantonCodeType }
     *     
     */
    public void setCanton(CantonCodeType value) {
        this.canton = value;
    }

    /**
     * Gets the value of the municipality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipality() {
        return municipality;
    }

    /**
     * Sets the value of the municipality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipality(String value) {
        this.municipality = value;
    }

    /**
     * Gets the value of the subunitOfLandRegister property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubunitOfLandRegister() {
        return subunitOfLandRegister;
    }

    /**
     * Sets the value of the subunitOfLandRegister property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubunitOfLandRegister(String value) {
        this.subunitOfLandRegister = value;
    }

    /**
     * Gets the value of the fosNr property.
     * 
     */
    public int getFosNr() {
        return fosNr;
    }

    /**
     * Sets the value of the fosNr property.
     * 
     */
    public void setFosNr(int value) {
        this.fosNr = value;
    }

    /**
     * Gets the value of the metadataOfGeographicalBaseData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetadataOfGeographicalBaseData() {
        return metadataOfGeographicalBaseData;
    }

    /**
     * Sets the value of the metadataOfGeographicalBaseData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetadataOfGeographicalBaseData(String value) {
        this.metadataOfGeographicalBaseData = value;
    }

    /**
     * Gets the value of the landRegistryArea property.
     * 
     */
    public int getLandRegistryArea() {
        return landRegistryArea;
    }

    /**
     * Sets the value of the landRegistryArea property.
     * 
     */
    public void setLandRegistryArea(int value) {
        this.landRegistryArea = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link MultiSurfacePropertyTypeType }
     *     
     */
    public MultiSurfacePropertyTypeType getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultiSurfacePropertyTypeType }
     *     
     */
    public void setLimit(MultiSurfacePropertyTypeType value) {
        this.limit = value;
    }

    /**
     * Gets the value of the restrictionOnLandownership property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restrictionOnLandownership property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestrictionOnLandownership().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RestrictionOnLandownershipType }
     * 
     * 
     */
    public List<RestrictionOnLandownershipType> getRestrictionOnLandownership() {
        if (restrictionOnLandownership == null) {
            restrictionOnLandownership = new ArrayList<RestrictionOnLandownershipType>();
        }
        return this.restrictionOnLandownership;
    }

    /**
     * Gets the value of the planForLandRegister property.
     * 
     * @return
     *     possible object is
     *     {@link MapType }
     *     
     */
    public MapType getPlanForLandRegister() {
        return planForLandRegister;
    }

    /**
     * Sets the value of the planForLandRegister property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapType }
     *     
     */
    public void setPlanForLandRegister(MapType value) {
        this.planForLandRegister = value;
    }

    /**
     * Gets the value of the planForLandRegisterMainPage property.
     * 
     * @return
     *     possible object is
     *     {@link MapType }
     *     
     */
    public MapType getPlanForLandRegisterMainPage() {
        return planForLandRegisterMainPage;
    }

    /**
     * Sets the value of the planForLandRegisterMainPage property.
     * 
     * @param value
     *     allowed object is
     *     {@link MapType }
     *     
     */
    public void setPlanForLandRegisterMainPage(MapType value) {
        this.planForLandRegisterMainPage = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocumentType }
     * 
     * 
     */
    public List<DocumentType> getReference() {
        if (reference == null) {
            reference = new ArrayList<DocumentType>();
        }
        return this.reference;
    }

    /**
     * Gets the value of the extensions property.
     * 
     * @return
     *     possible object is
     *     {@link Extensions }
     *     
     */
    public Extensions getExtensions() {
        return extensions;
    }

    /**
     * Sets the value of the extensions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Extensions }
     *     
     */
    public void setExtensions(Extensions value) {
        this.extensions = value;
    }

}
